# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/fetsySeller
    docker:
      - image: circleci/node:14.8.0
        environment:
          PGHOST: 127.0.0.1
          PGUSER: joselopez
          # NODE_ENV: test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: joselopez
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: joselopez
    steps:
      - checkout
      # Download and cache dependencies
      - run: npm install
      - run:
          name: Install postgress client
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client
      # Wait for Postgres connection to open.
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: npm run db:setup
      - run: npm run db:seed
      - run: npm test